### ISSUE TITLE
Missing m4 files

### ISSUE THREAD

**Issue by tobast** [stephenrkell/libdwarfpp#10]
There seems to be two files missing from the `m4` directory, in order to be able to compile easily the project:
- `ax_cxx_compile_stdcxx.m4`, available [here](https://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx.m4),
- `ax_cxx_compile_stdcxx_14.m4`, available [here](https://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx_14.m4)

**Comment by stephenrkell** [comment]
Thanks for this. In keeping with the inclusion of autogen.sh but not configure or Makefile.in, I have been preferring that people obtain these macros locally, e.g. by installing autoconf-archive or a similar package.

Incidentally this is what at least one other person recommends. :-) 
https://stackoverflow.com/questions/25473870/should-aclocal-m4-go-in-source-control

Should I simply document that more clearly? Or is there a good case for checking in these files?

**Comment by stephenrkell** [comment]
I remain open-minded about this, but closing the issue for now.
