### ISSUE TITLE
`Dwarf_Frame_Op3` removed in upstream libdwarf

### ISSUE THREAD

**Issue by tobast** [stephenrkell/libdwarfpp#13]
It seems that on 2018-06-12, libdwarf upstream decided to remove `Dwarf_Frame_Op3`:

> 2018-06-12 David Anderson
>     * libdwarf.h.in: Removed Dwarf_Frame_Op3
>       struct declaration. It was never used
>       and was a bad idea. A functional interface
>       is a likely replacement.

See [this commit `594139760e`](https://github.com/tomhughes/libdwarf/commit/594139760e4d10f6589dc941a4e0b6de21fce42d).

This change prevents `libdwarfpp` from building on a system with up-to-date libdwarf.

**Comment by stephenrkell** [comment]
Thanks for the report. Looks like the quick fix is to define an equivalent structure ourselves. I'll put this on my queue.

Out of interest, is the submodule'd libdwarf old enough that this is a problem (i.e. you needed to use the current one)? No doubt I should update that too... or just hurry up and replace libdwarf with libdw (#12).

**Comment by stephenrkell** [comment]
An attempted fix is now in 0936618.

**Comment by stephenrkell** [comment]
This seems to be working fine, so closing.
